services:
  postgres_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"]
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5

  backend:
    image: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    # user: "${UID}:${GID}"
    # command: bash -c "alembic upgrade head &&
    #              uvicorn main:app --host 0.0.0.0 --port 8000"
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    depends_on:
      - postgres_database
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
volumes:
  pgdata: