[project]
name = "database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiosqlite>=0.21.0",
    "asyncpg>=0.30.0",
    "fastapi-users[oauth,sqlalchemy]>=14.0.1",
    "psycopg2-binary>=2.9.10",
]
